### ISSUE TITLE
Could you give an example for hot reload？

### ISSUE THREAD

**Issue by sparkingarthur** [Kindrat/serving#3]
First of all, thank you for providing a way to dynamically load the models.
[https://github.com/tensorflow/serving/pull/774](url)
Please forgive me for being a newbie, could you please give me an example of how to use it? （Serving API HandleReloadConfigRequest method）
Do I need to re-edit the code and recompile or there is a much simpler way to config a hot-reload tf serving?

**Comment by Kindrat** [comment]
There is no way to "configure" hot reloading. It's a RPC API and needs to be compiled with serving. From client side you need to pass ReloadConfigRequest protobuf object

**Comment by sparkingarthur** [comment]
Thx a lot. I've written an [example](https://github.com/sparkingarthur/serving/blob/master/tensorflow_serving/example/hot_reload_grpc_example.py) in python for gRPC reload.
